version: 3.7
services:
  app:
    container_name: infodota_container
    build: .
    volumes:
      - ./app
    ports:
      - 80:80
  db:
    image: postgres:latest
    container_name: db_infodota
    restart: unless-started
    
